# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180227_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Author Name'),
        ),
    ]
