# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.5 on 2018-05-16 07:06
=======
# Generated by Django 1.11.5 on 2018-05-11 15:44
>>>>>>> 066ea74d4f34c315cab0fb653e6f24dcbc7806ea
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180421_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
